import http from 'node:http';
import crypto from 'node:crypto';
const PORT=Number(process.env.PORT||10000);
const env=k=>(process.env[k]||'').trim();
const allowedOrigin=env('FRONTEND_ORIGIN')||'*';
const cors={'Access-Control-Allow-Origin':allowedOrigin,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, OPTIONS','Access-Control-Max-Age':'600','Vary':'Origin'};
const security={'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Cache-Control':'no-store'};
const rateBuckets=new Map();
function rateLimited(req){const now=Date.now();const key=req.socket.remoteAddress||'unknown';const current=rateBuckets.get(key);if(!current||now-current.startedAt>=60000){rateBuckets.set(key,{startedAt:now,count:1});return false;}current.count+=1;return current.count>60;}
const jsonHeaders={'Content-Type':'application/json; charset=utf-8',...cors,...security};
const withTimeout=(ms)=>AbortSignal.timeout(ms);
const providers=[['allegro','Allegro','account',['ALLEGRO_CLIENT_ID','ALLEGRO_CLIENT_SECRET']],['ebay','eBay','live-search',['EBAY_CLIENT_ID','EBAY_CLIENT_SECRET']],['amazon','Amazon','account',['AMAZON_LWA_CLIENT_ID','AMAZON_LWA_CLIENT_SECRET']],['olx','OLX','account',['OLX_CLIENT_ID','OLX_CLIENT_SECRET']],['temu','Temu','account',['TEMU_APP_KEY','TEMU_APP_SECRET']],['ceneo','Ceneo','benchmark',['CENEO_API_KEY']],['erli','ERLI','account',['ERLI_API_KEY']],['empik','Empik','account',['EMPIK_API_KEY']],['kaufland','Kaufland','account',['KAUFLAND_CLIENT_KEY','KAUFLAND_SECRET_KEY']]];
const providerIds=new Set(providers.map(([id])=>id));
function health(){return providers.map(([id,name,mode,keys])=>{const configured=keys.every(env);const liveAdapter=id==='ebay';const status=liveAdapter?(configured?'configured':'missing-credentials'):'not-implemented';return {id,name,mode,configured,status,message:liveAdapter?(configured?'Live eBay connector configured.':'Credentials required in Render environment.'):(configured?'Credentials present; live-search adapter is not implemented yet.':'Provider registered; live-search adapter is not implemented yet.')};});}
function json(res,status,body){res.writeHead(status,jsonHeaders);res.end(JSON.stringify(body));}
let ebayToken=null; let ebayTokenExpiresAt=0;
async function getEbayApplicationToken(){
  if(ebayToken&&Date.now()<ebayTokenExpiresAt-60000)return ebayToken;
  const basic=Buffer.from(env('EBAY_CLIENT_ID')+':'+env('EBAY_CLIENT_SECRET')).toString('base64');
  const tokenRes=await fetch('https://api.ebay.com/identity/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+basic,'Content-Type':'application/x-www-form-urlencoded'},signal:withTimeout(10000),body:new URLSearchParams({grant_type:'client_credentials',scope:'https://api.ebay.com/oauth/api_scope'})});
  if(!tokenRes.ok){const detail=await tokenRes.text().catch(()=> '');throw new Error('eBay OAuth HTTP '+tokenRes.status+(detail?' '+detail.slice(0,240):''));}
  const token=await tokenRes.json();
  if(!token.access_token)throw new Error('eBay OAuth response missing access_token');
  ebayToken=token.access_token; ebayTokenExpiresAt=Date.now()+Number(token.expires_in||7200)*1000;
  return ebayToken;
}
async function ebaySearch(q,limit){const accessToken=await getEbayApplicationToken();const url=new URL('https://api.ebay.com/buy/browse/v1/item_summary/search');url.searchParams.set('q',q);url.searchParams.set('limit',String(limit));const r=await fetch(url,{headers:{Authorization:'Bearer '+accessToken,'Accept-Language':'pl-PL','X-EBAY-C-MARKETPLACE-ID':'EBAY_PL'},signal:withTimeout(12000)});if(r.status===401){ebayToken=null;ebayTokenExpiresAt=0;throw new Error('eBay Browse API HTTP 401; OAuth token rejected');}if(!r.ok){const detail=await r.text().catch(()=> '');throw new Error('eBay Browse API HTTP '+r.status+(detail?' '+detail.slice(0,240):''));}const data=await r.json();return (data.itemSummaries||[]).map(x=>({id:'ebay:'+x.itemId,productId:x.epid||x.itemId,title:x.title||'',price:Number(x.price?.value),store:'eBay',category:x.categories?.[0]?.categoryName||'eBay',condition:(x.condition||'').toLowerCase().includes('new')?'new':'unknown',availability:'unknown',sourceId:'ebay',sourceUrl:x.itemWebUrl||x.itemAffiliateWebUrl||'',observedAt:new Date().toISOString(),shippingIn:Number(x.shippingOptions?.[0]?.shippingCost?.value)||0})).filter(x=>x.title&&Number.isFinite(x.price)&&x.sourceUrl);}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Request-Id',crypto.randomUUID());if(rateLimited(req))return json(res,429,{error:'Rate limit exceeded',retryAfterSeconds:60});if(req.method==='OPTIONS'){res.writeHead(204,cors);return res.end();}const u=new URL(req.url||'/', 'http://'+(req.headers.host||'localhost'));try{if(u.pathname==='/health')return json(res,200,{ok:true,service:'extra-szpieg-api',time:new Date().toISOString()});if(u.pathname==='/api/marketplaces/health')return json(res,200,{sources:health(),generatedAt:new Date().toISOString()});if(u.pathname==='/api/marketplaces/search'){const q=(u.searchParams.get('q')||'').trim();if(!q)return json(res,400,{error:'q is required'});if(q.length>200)return json(res,400,{error:'q is too long',maxLength:200});const requested=(u.searchParams.get('marketplace')||'').trim().toLowerCase();if(requested&&!providerIds.has(requested))return json(res,400,{error:'Unknown marketplace',marketplace:requested,allowed:[...providerIds]});const parsedLimit=Number(u.searchParams.get('limit')||20);const limit=Number.isFinite(parsedLimit)?Math.min(50,Math.max(1,Math.floor(parsedLimit))):20;const selectedProvider=requested||'ebay';if(selectedProvider==='ebay'&&env('EBAY_CLIENT_ID')&&env('EBAY_CLIENT_SECRET')){const results=await ebaySearch(q,limit);return json(res,200,{query:q,results,sources:health(),selectedProvider,generatedAt:new Date().toISOString()});}return json(res,200,{query:q,results:[],sources:health(),selectedProvider,generatedAt:new Date().toISOString(),message:selectedProvider==='ebay'?'No configured live-search provider. Configure eBay credentials for the first live connector.':'Provider is registered but has no live-search adapter yet.'});}return json(res,404,{error:'Not found'});}catch(e){return json(res,502,{error:e instanceof Error?e.message:'Marketplace gateway failed'});}});
server.listen(PORT,()=>console.log('Extra Szpieg API listening on '+PORT));