const USER_AGENT='Extra-Szpieg/0.5 marketplace-discovery (+live)';
const REQUEST_TIMEOUT_MS=12000;
const clean=v=>String(v??'').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
const abs=(u,base)=>{try{return new URL(String(u),base).href}catch{return null}};
const normalizeTitle=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const priceFrom=t=>{const matches=[...clean(t).matchAll(/(?:PLN|zł)\s*(\d[\d\s.]*(?:,\d{2})?)|(\d[\d\s.]*(?:,\d{2})?)\s*(?:PLN|zł)/gi)];for(const m of matches){const raw=m?.[1]||m?.[2];if(!raw)continue;const n=Number(raw.replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'));if(Number.isFinite(n)&&n>0&&n<10000000)return n}return null};
const availabilityFrom=v=>{const s=String(v??'').toLowerCase();if(s.includes('outofstock')||s.includes('out of stock'))return'out_of_stock';if(s.includes('limited'))return'limited';if(s.includes('instock')||s.includes('in stock'))return'in_stock';return'unknown'};
const conditionFrom=v=>{const s=String(v??'').toLowerCase();if(s.includes('refurb'))return'refurbished';if(s.includes('used'))return'used';if(s.includes('openbox')||s.includes('open box'))return'open_box';if(s.includes('new'))return'new';return'unknown'};
function flatten(v,o=[]){if(Array.isArray(v))v.forEach(x=>flatten(x,o));else if(v&&typeof v==='object'){o.push(v);if(v['@graph'])flatten(v['@graph'],o)}return o}
function productObjects(html){const out=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{out.push(...flatten(JSON.parse(m[1])))}catch{}}return out}
function mapObject(x,base,id,name){const offers=x.offers??{},title=clean(x.name||x.title),url=abs(x.url||offers.url,base),price=Number(offers.price??x.price);if(!title||!url||!Number.isFinite(price)||price<=0)return null;const brand=typeof x.brand==='string'?x.brand:clean(x.brand?.name),model=clean(x.model||x.mpn),ean=clean(x.gtin13||x.gtin12||x.gtin||x.gtin14)||undefined;return{id:id+'-'+Buffer.from(url).toString('base64url').slice(0,32),productId:ean?'EAN:'+ean:id+'-'+Buffer.from(normalizeTitle(title)).toString('base64url').slice(0,24),ean,sku:clean(x.sku||x.mpn)||undefined,title,brand:brand||undefined,model:model||undefined,store:name,category:clean(x.category)||'unknown',price,currency:'PLN',condition:conditionFrom(x.itemCondition||offers.itemCondition),availability:availabilityFrom(offers.availability),sourceId:id,sourceUrl:url,observedAt:new Date().toISOString()}}
function parse(html,base,id,name,limit){const out=[],seen=new Set();for(const x of productObjects(html)){const item=mapObject(x,base,id,name);if(!item||seen.has(item.sourceUrl))continue;seen.add(item.sourceUrl);out.push(item);if(out.length>=limit)return out}const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]{0,1800}?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<limit){const text=clean(m[2].replace(/<[^>]+>/g,' ')),price=priceFrom(text),url=abs(m[1],base);if(!url||price===null||text.length<4||seen.has(url))continue;const title=text.replace(/(?:PLN|zł)\s*\d[\d\s.,]*/ig,'').trim().slice(0,220);if(title.length<4)continue;seen.add(url);out.push({id:id+'-'+Buffer.from(url).toString('base64url').slice(0,30),productId:id+'-'+Buffer.from(normalizeTitle(title)).toString('base64url').slice(0,22),title,store:name,category:'unknown',price,currency:'PLN',condition:'unknown',availability:'unknown',sourceId:id,sourceUrl:url,observedAt:new Date().toISOString()})}return out}
export function createPublicAdapter({id,name,buildUrl}){return{id,configured:()=>true,authStatus:()=>({status:'configured',connection:'public-web',detail:null}),async search(query,limit=20){const q=String(query||'').trim();if(!q)throw new Error(name+' search query is empty.');const url=buildUrl(q),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const r=await fetch(url,{headers:{'User-Agent':USER_AGENT,Accept:'text/html,application/xhtml+xml,application/json'},signal:controller.signal});if(!r.ok)throw new Error(name+' public search HTTP '+r.status);const results=parse(await r.text(),url,id,name,Math.min(50,Math.max(1,Number(limit)||20)));if(!results.length)throw new Error(name+' public search returned no parseable product offers.');return results}catch(error){if(error?.name==='AbortError')throw new Error(name+' public search timed out after '+REQUEST_TIMEOUT_MS+'ms');throw error}finally{clearTimeout(timer)}}}};
