import { useEffect, useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { Activity, Bell, BrainCircuit, ChevronRight, ExternalLink, Heart, LayoutDashboard, Radar, Search, Settings2, ShieldCheck, Sparkles, Target, TrendingDown, Wallet, Zap } from 'lucide-react';
import type { DealAnalysis } from './domain/deal';
import { getSourceAdapters } from './sources/sourceRegistry';
import { runScan } from './services/scanEngine';
import { analyzeDealLocally } from './services/ai/localDealAnalyst';
import { decideOpportunity } from './services/decision/opportunityEngine';
import { loadState, saveState } from './services/persistence/localState';
import { allowedTransitions, initialDealActionState, transitionDealAction, type DealActionState } from './services/decision/actionState';
import { buildAlerts } from './services/alerts/alertEngine';
import { summarizeEvidence, provenanceLabel, sourceTruthLabel } from './services/evidence/provenance';
import './visual-master.css';

const categories = ['Wszystko', 'Audio', 'Laptopy', 'Smartfony', 'Gaming', 'TV', 'AGD', 'Hobby'];
const money = (value: number) => `${Math.round(value).toLocaleString('pl-PL')} zł`;
const marketplaceApi = String(import.meta.env.VITE_MARKETPLACE_API_URL || 'https://extra-szpieg-api.onrender.com').replace(/\/$/, '');

export default function App() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('Wszystko');
  const initial = loadState();
  const [watched, setWatched] = useState<string[]>(initial.watched); const [actions, setActions] = useState<Record<string, DealActionState>>(initial.actions); const [deals, setDeals] = useState<DealAnalysis[]>(initial.deals);
  const [selected, setSelected] = useState<DealAnalysis | null>(null); const [scanning, setScanning] = useState(false);
  const [scanInfo, setScanInfo] = useState(initial.savedAt ? `Odtworzono zapis z ${new Date(initial.savedAt).toLocaleString('pl-PL')}.` : 'Silnik gotowy. Czekam na skan.'); const [budget, setBudget] = useState(initial.budget);
  const [minRoi, setMinRoi] = useState(initial.minRoi); const [view, setView] = useState<'radar' | 'portfolio'>('radar'); const [section, setSection] = useState<'all' | 'drops' | 'watched' | 'alerts'>('all');
  useEffect(() => { saveState({ deals, watched, actions, budget: Number.isFinite(budget) && budget >= 0 ? budget : 0, minRoi: Number.isFinite(minRoi) ? Math.max(0, Math.min(80, minRoi)) : 0, savedAt: new Date().toISOString() }); }, [deals, watched, actions, budget, minRoi]);
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); document.querySelector<HTMLInputElement>('.search input')?.focus(); }
      if (event.key === 'Escape') setSelected(null);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);
  const alertIds = useMemo(() => new Set(buildAlerts(deals).map(a => a.dealId)), [deals]);
  const alertCount = alertIds.size;
  const filtered = useMemo(() => deals.filter(d => (category === 'Wszystko' || d.category === category)).filter(d => `${d.title} ${d.store} ${d.category} ${d.brand ?? ''}`.toLowerCase().includes(query.toLowerCase())).filter(d => d.roiPct >= minRoi).filter(d => section === 'all' || (section === 'drops' ? d.discountPct >= 10 : section === 'watched' ? watched.includes(d.id) : alertIds.has(d.id))).sort((a,b)=>b.score-a.score), [deals,category,query,minRoi,section,watched,alertIds]);
  const best = filtered[0]; const totalPotential = deals.reduce((s,d)=>s+Math.max(0,d.potentialProfit),0);
  const portfolio = filtered.filter(d=>Number.isFinite(d.price)&&d.price>0&&d.price<=Math.max(0,budget)).slice(0,6); const portfolioCost=portfolio.reduce((s,d)=>s+d.price,0); const portfolioProfit=portfolio.reduce((s,d)=>s+Math.max(0,d.potentialProfit),0);
  const runSzpieg = async()=>{const effectiveQuery=query.trim() || String(import.meta.env.VITE_ALLEGRO_SEARCH_PHRASE ?? '').trim();if(!effectiveQuery){setScanInfo('Wpisz produkt lub frazę, np. iPhone 15, RTX 4070 albo MacBook.');return;}setScanning(true);setScanInfo('Łączenie ze źródłami → normalizacja → kalkulacja → ranking...');try{const r=await runScan(getSourceAdapters(), effectiveQuery);setDeals(r.deals);const firstError=r.errors[0];setScanInfo(r.offersFound?`${r.offersFound} ofert • ${r.durationMs} ms • ${r.errors.length?'częściowy wynik':'pipeline OK'}`:(firstError||'Brak ofert z aktywnych źródeł.'));}catch(error){setScanInfo(error instanceof Error?error.message:'Skan zakończony błędem.');}finally{setScanning(false);}};
  const toggleWatch=(id:string)=>setWatched(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id]);
  const actionFor=(deal:DealAnalysis):DealActionState=>actions[deal.id] ?? initialDealActionState(true);
  const setDealAction=(deal:DealAnalysis,next:DealActionState)=>setActions(current=>{const previous=current[deal.id] ?? initialDealActionState(true); return {...current,[deal.id]:transitionDealAction(previous,next)};});
  const actionAllowed=(deal:DealAnalysis,next:DealActionState)=>{const current=actionFor(deal); return current===next || allowedTransitions(current).includes(next);};
  const selectedOpportunity = selected ? decideOpportunity(selected) : null;
  const selectedProvenance = selected ? summarizeEvidence(selected) : null;
  return <div className="app"><aside>
    <div className="brand"><div className="logo"><Radar/></div><div><b>EXTRA SZPIEG</b><span>PRIVATE DEAL INTELLIGENCE</span></div></div><div className="modeLabel">COMMAND CENTER</div>
    <nav><button className={view==='radar'?'navItem active':'navItem'} onClick={()=>{setView('radar');setSection('all')}}><LayoutDashboard/> Radar okazji</button><button className="navItem" onClick={()=>{setSection('all');runSzpieg()}}><Zap/> Skanuj rynek</button><button className="navItem" onClick={()=>{setView('radar');setSection('drops');setQuery('');setMinRoi(0);setCategory('Wszystko');}}><TrendingDown/> Spadki cen</button><button className="navItem" onClick={()=>{setView('radar');setSection('watched');setQuery('');setMinRoi(0);setCategory('Wszystko');}}><Heart/> Obserwowane <i>{watched.length}</i></button><button className="navItem" onClick={()=>{setView('radar');setSection('alerts');setMinRoi(15);}}><Bell/> Alerty <i>{alertCount}</i></button><button className={view==='portfolio'?'navItem active':'navItem'} onClick={()=>{setView('portfolio');setSection('all')}}><Wallet/> Profit Lab</button></nav>
    <div className="navDivider"/><button className="navItem" onClick={()=>setScanInfo('AI Analyst: analiza lokalna aktywna. Wyniki są deterministyczne i nie są generowane przez zewnętrzny model.') }><BrainCircuit/> AI Analyst</button><button className="navItem" onClick={()=>setScanInfo('Ustawienia: budżet, minimalny ROI i obserwowane oferty są zapisywane lokalnie w tej przeglądarce.') }><Settings2/> Ustawienia</button>
    <div className="sideBottom"><span className="onlineDot"/><span><b>CORE ONLINE</b><small>Deterministic intelligence active</small></span></div>
  </aside><main>
    <header className="topbar"><div><div className="eyebrow"><span className="liveDot"/> PRIVATE DEAL OPS · 01</div><h1>{view==='radar'?'Radar okazji':'Profit Lab'}</h1><p className="muted">{view==='radar'?'Nie szukaj promocji. Szukaj przewagi cenowej.':'Policz, co możesz kupić za swój kapitał i jaki potencjał ma koszyk.'}</p></div><div className="topActions"><button className="ghostButton" onClick={()=>window.location.assign(marketplaceApi + '/api/allegro/oauth?action=authorize&returnTo=' + encodeURIComponent(window.location.origin))}>POŁĄCZ ALLEGRO</button><div className="budgetMini"><Wallet/><span>Budżet <b>{money(budget)}</b></span></div><button className="scanButton" onClick={runSzpieg} disabled={scanning}><Zap/>{scanning?'SZPIEG PRACUJE':'URUCHOM SZPIEGA'}</button></div></header>
    <section className="scanStatus"><span className={scanning?'pulse':''}/><Activity/><b>{scanning?'LIVE SCAN':'ENGINE READY'}</b><span>{scanInfo}</span><em>PRIVATE BUILD · {deals.length ? `${alertCount} ALERTS` : 'NO LIVE DATA'}</em></section>
    {view==='radar'?<>
      <section className="heroGrid"><div className="heroCommand"><div className="heroGlow"/><div className="heroCopy"><span className="micro">SZPIEG INTELLIGENCE</span><h2>Znajdź coś, czego inni jeszcze nie zauważyli.</h2><p>Jeden skan przepuszcza oferty przez cenę rynkową, koszty, potencjalną odsprzedaż, ROI, ryzyko i Szpieg Score.</p><button onClick={runSzpieg} disabled={scanning}><Zap/>{scanning?'SKANOWANIE...':'SKANUJ RYNEK'}</button></div><div className="radarVisual"><div className="radarRing r1"/><div className="radarRing r2"/><div className="radarRing r3"/><div className="radarSweep"/><div className="radarCore"><Radar/></div><span className="signal s1">+39% ROI</span><span className="signal s2">96 SCORE</span><span className="signal s3">−31% MARKET</span></div></div>
      <div className="bestDealPanel"><div className="panelLabel"><Target/> CURRENT BEST SIGNAL</div>{best?<><div className="bestScore">{best.score}<small>/100</small></div><h3>{best.title}</h3><p>{best.store} · {best.verdict}</p><div className="bestNumbers"><div><span>BUY</span><b>{money(best.price)}</b></div><div><span>PROFIT</span><b>{money(best.potentialProfit)}</b></div><div><span>ROI</span><b>{best.roiPct.toFixed(1)}%</b></div></div><div className="marketSpectrum"><div className="spectrumLabels"><span>LOW</span><span>MEDIAN</span><span>HIGH</span></div><div className="spectrumTrack"><i/><b/></div><div className="spectrumValues"><span>{money(best.price)}</span><span>{money(best.marketMedian??best.price)}</span></div></div><button className="ghostButton" onClick={()=>setSelected(best)}>Otwórz pełną analizę <ChevronRight/></button></>:<div className="emptyBest"><Sparkles/><b>Brak aktywnego sygnału</b><span>Uruchom pierwszy skan.</span></div>}</div></section>
      <section className="intelRibbon"><span><i/> SIGNAL PIPELINE</span><b>DISCOVERY</b><em>→</em><b>NORMALIZATION</b><em>→</em><b>ANALYSIS</b><em>→</em><b>DECISION</b></section><section className="stats"><div><span>OFERTY W SKANIE</span><strong>{deals.length||'—'}</strong><small>normalizowane</small></div><div><span>MEGA OKAZJE</span><strong>{deals.filter(d=>d.score>=90).length||'—'}</strong><small>score ≥ 90</small></div><div><span>POTENCJALNY ZYSK</span><strong>{deals.length?money(totalPotential):'—'}</strong><small>przed podatkiem / ryzykiem</small></div><div><span>OBSERWOWANE</span><strong>{watched.length}</strong><small>aktywnych watchów</small></div></section>
      <section className="controlBar"><div className="search"><Search/><input aria-label="Szukaj ofert" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zapytaj Szpiega o produkt, markę, sklep..."/><kbd>⌘ K</kbd></div><div className="roiControl"><span>MIN ROI</span><b>{minRoi}%</b><input aria-label="Minimalny ROI" type="range" min="0" max="80" value={minRoi} onChange={e=>setMinRoi(Number(e.target.value))}/></div></section><div className="chips">{categories.map(c=><button className={category===c?'chip activeChip':'chip'} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div>
      <div className="sectionHead"><div><div className="eyebrow">RANKED SIGNALS</div><h2>Najlepsze okazje</h2><p className="muted">Najpierw przewaga. Potem zysk. Dopiero na końcu marketingowa promocja.</p></div><div className="fresh"><span/>{deals.length?'wyniki aktualnego skanu':'oczekuje na dane'}</div></div>
      {deals.length===0?<div className="empty heroEmpty"><Radar/><h3>Szpieg czeka na rozkaz</h3><p>To jest prywatne centrum zakupowe. Nie pokazujemy fikcyjnych ofert ani fikcyjnych statystyk.</p><button className="dealBtn" onClick={runSzpieg}>URUCHOM PIERWSZY SKAN <Zap/></button></div>:<section className="dealTable">{filtered.map((d,i)=><article className="dealRow" key={d.id}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="dealIdentity"><div className="miniProduct"><Sparkles/></div><div><h3>{d.title}</h3><p>{d.store} · {d.category} · {d.condition}</p></div></div><div className="metric"><span>BUY</span><b>{money(d.price)}</b></div><div className="metric"><span>MARKET</span><b>{money(d.marketMedian??d.price)}</b></div><div className="metric profit"><span>PROFIT</span><b>+{money(d.potentialProfit)}</b></div><div className="metric"><span>ROI</span><b>{d.roiPct.toFixed(1)}%</b></div><div className="score"><strong>{d.score}</strong><small>/100</small><span>{d.risk.toUpperCase()}</span><i style={{'--score':d.score} as CSSProperties}/></div><button aria-label={watched.includes(d.id)?'Usuń z obserwowanych':'Obserwuj ofertę'} className="watch" onClick={()=>toggleWatch(d.id)}><Heart fill={watched.includes(d.id)?'currentColor':'none'}/></button><button aria-label="Otwórz analizę" className="rowOpen" onClick={()=>setSelected(d)}><ChevronRight/></button></article>)}</section>}